// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type CreatorCert struct {
	UserID    int32
	Status    sql.NullInt32
	Link      sql.NullString
	IsBlocked sql.NullInt32
}

type LoginHistory struct {
	ID        int32
	CreatedAt time.Time
	UserID    int32
}

type Oauth struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
	OauthID   string
	OauthType string
	Version   int32
}

type Octet struct {
	UserID     int32
	NetType    string
	WalletAddr string
	Memo       sql.NullString
}

type Service struct {
	ID           int32
	Name         string
	Symbol       string
	Decimals     int32
	Image        sql.NullString
	IsNative     int32
	ContractAddr sql.NullString
	NetType      sql.NullString
	WalletType   sql.NullString
}

type Transaction struct {
	ID          int32
	FromID      int32
	ToID        int32
	ServiceID   int32
	Memo        sql.NullString
	TotalAmount int64
}

type TransactionDetail struct {
	TransactionID int32
	From          string
	To            string
	Amount        int64
	IsOnchain     int32
	Txhash        sql.NullString
	Status        int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Nickname  sql.NullString
	Email     string
	Type      string
	Verified  int32
	IsLocked  int32
	Picture   sql.NullString
}

type UserBalance struct {
	ID        int32
	UserID    int32
	ServiceID int32
	Amount    int64
}

type UserPw struct {
	ID         int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     int32
	SecPw      sql.NullString
	WalletAddr sql.NullString
}

type UserService struct {
	UserID    int32
	ServiceID int32
}

type UserWallet struct {
	ID           int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
	UserID       int32
	WalletAddr   string
	SecPk        sql.NullString
	IsIntegrated int32
	WalletType   sql.NullString
	NetType      sql.NullString
}
